### PR TITLE
Start ODEGenProg

### PR DESCRIPTION
**Pull request by MMichaelVdV**

### CODE REVIEW

**Comment by MichielStock** [comment]
The book I use for my course has a whole chapter on genetic programming, including a package to make it easy to process symbols. Mail me if you want a scan of these chapters.

**Comment by MichielStock** [comment]
- the documentation might be extented a bit...
- can you just yield functions with `GrammarRules`? Can you use the mean squared error between the derivative of the generated function and your target function over a grid of function evaluations? You can use forward differentiation to do this.
- you can make a simple animation if you want to: https://docs.juliaplots.org/latest/animations/

**Comment by MichielStock** [comment]
The notebook looks quite promising, maybe put some of it in the `src/`? 

You might also use dashes to plot your solution, so we can better compare with the exact solution.

**Comment by MichielStock** [comment]
Needs to be reviewed tomorrow by @KobeDeTemmerman, @DouweDeVestele and @tjvneste.

**Comment by DouweDeVestele** [comment]
I finished reviewing and I think it's a very interesting, elaborated project!

It seems a difficult but very practical problem. I really like the idea of programs solving differential equations instead of doing it by hand.
I opened a pull request with some minor fixes for typos and extra comments.

I learned while reviewing, thanks!

**Comment by MMichaelVdV** [comment]
> 
> 
> I finished reviewing and I think it's a very interesting, elaborated project!
> 
> It seems a difficult but very practical problem. I really like the idea of programs solving differential equations instead of doing it by hand.
> I opened a pull request with some minor fixes for typos and extra comments.
> 
> I learned while reviewing, thanks!

@DouweDeVestele  Thanks! I addressed your comments directly in the pull request.

**Comment by tjvneste** [comment]
I'm also finished with the feedback. It was indeed very informative to review your project! Good job and hope you get something from my comments as well :)

**Comment by MMichaelVdV** [comment]
> 
> 
> I'm also finished with the feedback. It was indeed very informative to review your project! Good job and hope you get something from my comments as well :)

Thanks!

**Comment by KobeDeTemmerman** [comment]
Congratulations, I really like your project. It is a really interesting topic and
I think you have solved it very well. I tried to make the documentation, but It 
doesn't seem to find the docstrings of the sourcecode. Because nobody else mentioned
it I think that it is my mistake. I looked at the make.jl file but I didn't see anything that could 
cause this, so again it's propably something I did. I looked at the documentation
in the source code and I think it contains everything that it should contain. 
It is short and clear as it should be. This is not something essential, but 
in the notebook I would maybe explain the genotypes and the grammar a little more 
extensively, because it's really important that the reader knows what is 
actually optimized by the algorithm. 
But again, good job!

**Comment by MMichaelVdV** [comment]
> 
> 
> Congratulations, I really like your project. It is a really interesting topic and
> I think you have solved it very well. I tried to make the documentation, but It
> doesn't seem to find the docstrings of the sourcecode. Because nobody else mentioned
> it I think that it is my mistake. I looked at the make.jl file but I didn't see anything that could
> cause this, so again it's propably something I did. I looked at the documentation
> in the source code and I think it contains everything that it should contain.
> It is short and clear as it should be. This is not something essential, but
> in the notebook I would maybe explain the genotypes and the grammar a little more
> extensively, because it's really important that the reader knows what is
> actually optimized by the algorithm.
> But again, good job!

Thanks! I'm not sure the others tried to make the documentation. I'll have another look myself.

**Comment by DouweDeVestele** [comment]
@KobeDeTemmerman  @MMichaelVdV  I had no problems with the documentation.

**Pull request merged**
