### PR TITLE
start Maximum Flow

### PR DESCRIPTION
**Pull request by DouweDeVestele**
Initialize maximum flow project

### CODE REVIEW

**Comment by MichielStock** [comment]
Your notebook does not seem to work for me. I hope I did nothing wrong by looking at this source. You might use a drop-down menu instead of a checkbox for selecting the example problem.

Maybe add a hyperlink to the Wikipedia page in the documentation?

Otherwise, this is an excellent project. Good job!

**Comment by MichielStock** [comment]
Needs to be reviewed tomorrow by @MMichaelVdV and @csangara.

**Comment by csangara** [comment]
First, let me start off my review by congratulating you; what a great project!
In particular:
- The source code is well-documented with clear examples
- The unit testing is extensive
- The notebook demonstrates nice, practical examples that really illustrated the concepts

Some other comments:
- Is there a way to overload `augmenting_path` more so you don't have to define three more functions for multiple sources/sinks? I thought it might make the code cleaner, but perhaps it's not so straightforward to do.
- The notebook is a bit mathematical at times, and I think it will be easier to grasp if you add some layman's explanations before you present the math equations. For instance, the definition of residual networks can really benefit from this, because the concept is actually very simple, it just gets occluded by all these other notations.

Overall, I am in awe of the quality of this project. Well done!
(I will shortly make a pull request on minor changes I made to your source code and notebook.)

**Comment by MMichaelVdV** [comment]
I just finished looking at everything (I cloned the repo and looked at it locally). 

- I really like the didactic quality of the notebook. The problem is clearly explained in a thorough introduction. Concepts are supported by nice visualizations. Examples and applications are elaborately and clear. Maybe there is still room for a bit more interactivity but atm I don't have any concrete suggestions where to build that in.

- The code seems to be well-documented, tidy and comprehensible. 

- Your code seems to be robustly tested and all tests are working fine for me. 

Not sure what else you can actually improve here, the overall the quality of this project seems to be really high (referring to the rubric I think you pretty well optimized all 4 evaluation criteria).

**Comment by DouweDeVestele** [comment]
@csangara Thank you!

> * Is there a way to overload `augmenting_path` more so you don't have to define three more functions for multiple sources/sinks? I thought it might make the code cleaner, but perhaps it's not so straightforward to do.

I have also been thinking about it and in fact I could do it, but then I would add an extra node even it if it is not necessary and this will increase the running time (probably not very much). I don't know what would be better.

> * The notebook is a bit mathematical at times, and I think it will be easier to grasp if you add some layman's explanations before you present the math equations. For instance, the definition of residual networks can really benefit from this, because the concept is actually very simple, it just gets occluded by all these other notations.

You are right, I will improve that!

Thanks for the suggestions!

**Comment by DouweDeVestele** [comment]
@MMichaelVdV  Thank you for reviewing! I will have a look where I can make the notebook more interactive.

**Comment by DouweDeVestele** [comment]
Tried to make one big `augmenting_path` instead of the different methods, but was less straightforward and practical than I thought first, so I'll leave it like this.

**Pull request merged**
