### PR TITLE
SingleCellNMF

### PR DESCRIPTION
**Pull request by f6v**
Here I implement non-negative matrix factorization and demonstrate its utility on simulated single-cell ATAC-seq and RNA-seq data. Specific term in objective function allows aggregating sparse epigenetic signal:

Screenshot 2020-12-16 at 17 53 35

### CODE REVIEW

**Comment by f6v** [comment]
@MichielStock what is the best place to put sample data for the notebook? Like couple `csv` files.

**Comment by MichielStock** [comment]
> @MichielStock, what is the best place to put sample data for the notebook? Like couple `csv` files.

The best place is somewhere else ;-)
Can you illustrate the code on small examples coded in the notebook? If not, you can use the function `download` in Pluto to download a file.
Worst-case you can make a folder `data` in the repo but preferably not since this will bloat the repo.

**Comment by f6v** [comment]
@MichielStock thanks! I guess it's quite common to include the sample data with R packages, don't know much about Julia. But I can certainly download the files within a notebook.

**Comment by MichielStock** [comment]
You can do it, but it is just not tidy for our purposes.

**Comment by MichielStock** [comment]
- I get an error when running test.
- Your functions work with `DataFrames`, Would it not be more tidy if they work with matrices or abstract matrices and the user has to put them in the desired format. I would try to remove the dependency on `DataFrames`
- you might use unicode for your greek letters (alpha, gamma), though this is a matter of taste
- in the notebook, you can use the julia function `download` (but first check if the file exists`) you can also run UNIX commands via julia `run(\`cmd\`)` 
- sadly an error `MethodError: no method matching update_W_atac(::Array{Float64,2}, ::Array{Float64,2}`, but it looks quite impressive

So, fix the error and I think you are more or less set!

**Comment by f6v** [comment]
@MichielStock thanks!

Could you give me a hand, please? How do you run the tests and what's the full error look like? Maybe I'm doing it wrong?

```
julia> ]
(STMOZOO) pkg> activate .
(STMOZOO) pkg> test
```

And I get the following output:
image

**Comment by MichielStock** [comment]
Screen Shot 2020-12-24 at 11 47 00

This is what I get? It seems to be an ordinary Julia method error. Maybe I am not working on your latest version?

**Comment by f6v** [comment]
@MichielStock thanks!
https://github.com/MichielStock/STMOZOO/pull/12/commits/fdfede1e53459839c994b1b84f0fba288ce05ade was the right commit. Just to be sure I added a dead simple Docker image https://github.com/MichielStock/STMOZOO/pull/12/commits/a23aca4d9fd1e61f6053f763f13098b1004f4a03.

You can run it like so:
```
docker run -it iamfilippov/stmozoo
```

Which opens a Julia console inside the container. You can verify the tests by running:
```
julia> using Pkg; Pkg.test("STMOZOO")
```

Or just check out the latest commit on my branch and build the image locally. Let me know if this works!

EDIT: I've also tested it in fresh Linux VM. I don't see any reason why it wouldn't work unless It was a wrong commit.

**Comment by f6v** [comment]
@MichielStock as for `DataFrames`, I'd like the row names to be present in the result, so that users can reference modality loadings by the original gene or locus name. As far as I know, Julia 2d arrays don't support row names.

**Comment by MichielStock** [comment]
Needs to be reviewed tomorrow by @tjvneste, @kirstvh and @csangara

**Comment by tjvneste** [comment]
Probably easier if I comment here: 

- In general => good structure in the code 👍 
- I would document the functions a little more so that it is clear what exactly the inputs and outputs are for the different functions (or at least the main functions) 
- The if loops @ the beginning of some functions can probably be replaced by @asserts

**Comment by tjvneste** [comment]
Screenshot 2021-01-07 at 15 07 39
I tried to upload the documentation but it gave my this error. I don't know if this is my fault or if it is wrong?

**Comment by f6v** [comment]
@tjvneste thanks for the review!

> I would document the functions a little more so that it is clear what exactly the inputs and outputs are for the different functions (or at least the main functions)

You're right.

> The if loops @ the beginning of some functions can probably be replaced by @asserts

I chose throwing exceptions deliberately, since `ArgumentError` gives a clear indication that the function failed due to the invalid argument provided by the user. See https://stackoverflow.com/questions/117171/design-by-contract-using-assertions-or-exceptions https://stackoverflow.com/questions/117171/design-by-contract-using-assertions-or-exceptions

> I tried to upload the documentation but it gave my this error. I don't know if this is my fault or if it is wrong?

How did you do it?

**Comment by tjvneste** [comment]
> How did you do it?

I just ran the make.jl file and then opened the html.

**Comment by csangara** [comment]
Great project!
- The source code is really clean and well-structured, and there is sufficient testing
- The documentation gives a good overview to the problem
- The notebook is illustrative and to-the-point

Other remarks:
- I got this error when reading in the files: `ArgumentError: provide a valid sink argument`. I had to change the code to `rna_data = CSV.read(rna_file, DataFrame)` for it to work, but maybe it's just me.
- In the Pluto notebook, the code to generate markdown was still visible for me; it might look nicer if you made the code invisible and only showed the markdown.

I made some small changes to your documentation and notebook which you can see in the pull request.

**Comment by kirstvh** [comment]
Hi, 

I think you made a really nice project that covers an interesting subject!

•	Tidy code 
•	Tests did run well
•	Notebook together with documentation did clarify the concept for me, but additional info about inputs and outputs of functions in the documentation would help to better understand the entire code and functions

Some small remarks for the notebook:

•	Downloading the files for the notebook did not work for me with the “run” command, but it did work with “download” command
•	I got the following error in the cell where the data is reformed to a dataframe (error gives solution to problem):   `ArgumentError: provide a valid sink argument, like using DataFrames; CSV.read(source, DataFrame)`   


Kirsten

**Comment by f6v** [comment]
@csangara @kirstvh thanks! 
Have never seen the issue with loading CSV, will check it out.
As for `download`, it seems that the function is rather platform specific. It didn't work for me on macOS, so I opted out for `wget` with `run`.

**Comment by f6v** [comment]
@tjvneste 

I've checked and it rendered for me, so maybe it's a platform-specific issue.
image

**Pull request merged**
